Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.


In [1]:
import numpy as np

In [25]:
def ATP(vector,n,increasing):
    if increasing == False:
        matrix = np.matrix([x**(n-i-1) for x in vector for i in range(n)]).reshape(vector.size,n) 
    else:
        matrix = np.matrix([x**i for x in vector for i in range(n)]).reshape(vector.size,n) 
    return matrix   

In [22]:
vector = np.array([3,5,8,9,10,12])
n = 6

In [32]:
 Dec = ATP(vector,n,False)
print('The matrix is : \n',Dec)

The matrix is : 
 [[   243     81     27      9      3      1]
 [  3125    625    125     25      5      1]
 [ 32768   4096    512     64      8      1]
 [ 59049   6561    729     81      9      1]
 [100000  10000   1000    100     10      1]
 [248832  20736   1728    144     12      1]]


In [44]:
Inc = ATP(vector,n,True)
print('The matrix is : \n',Asc)

The matrix is : 
 [[     1      3      9     27     81    243]
 [     1      5     25    125    625   3125]
 [     1      8     64    512   4096  32768]
 [     1      9     81    729   6561  59049]
 [     1     10    100   1000  10000 100000]
 [     1     12    144   1728  20736 248832]]


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [42]:
def moving_avg(values,k):
    z = 1
    ma = np.convolve(values,np.ones(k),'valid')/k
    for i in ma:
        print('y{0}: {1:.2f}'.format(z,i))
        z+=1
        

In [43]:
values = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
moving_avg(values,k)

y1: 5.00
y2: 4.67
y3: 5.67
y4: 6.67
y5: 9.67
y6: 28.67
y7: 49.33
y8: 72.67
y9: 84.00
y10: 93.33
y11: 116.33
